[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deepeval_lm_harness"
version = "0.1.0"
authors = [
    { name = "Linus Beckhaus", email = "lmbeckhaus@gmail.com" }
]
description = "A framework for evaluating language models with support for deepeval metrics"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.10"

dependencies = [
    "accelerate>=0.29.1",
    "black>=24.1.0",
    "isort>=5.13.2",
    "datasets>=2.19.0",
    "evaluate>=0.4.0",
    "httpx>=0.23.3",
    "jsonlines",
    "numexpr",
    "numpy>=1.26.4",
    "peft>=0.2.0",
    "pybind11>=2.6.2",
    "pytablewriter",
    "sacrebleu>=1.5.0",
    "scikit-learn>=0.24.1",
    "sqlitedict>=2.1.0",
    "torch>=2.1.0",
    "torchvision>=0.16.0",
    "openai",
    "opencv-python-headless",
    "dill",
    "word2number",
    "more_itertools",
    "nltk",
    "sentencepiece",
    "tqdm",
    "tqdm-multiprocess",
    "transformers>=4.39.2",
    "transformers-stream-generator",
    "zstandard",
    "pyyaml",
    "Jinja2",
    "loguru",
    "hf_transfer",
    "tenacity",
    "wandb>=0.16.0",
    "tiktoken",
    "pydantic",
    "packaging",
    "zss",
    "protobuf",
    "sentence_transformers",
    "python-dotenv",
    "requests",
    "aiohttp",
    "pre-commit",
    "pandas",
    "deepeval>=3.7.0"
]

[project.optional-dependencies]
fast_inference = ["vllm>=0.11"]
audio = [
    "more-itertools",
    "editdistance",
    "zhconv",
    "librosa",
    "soundfile"
]
metrics = [
    "pywsd",
    "spacy",
    "anls",
    "rouge",
    "capture_metric",
    "Levenshtein",
]
qwen = ["qwen-vl-utils", "decord", "librosa", "soundfile"]
longbench = ["jieba", "fuzzywuzzy", "rouge"]
ruler = ["nltk", "wonderwords", "scipy"]
testing = ["pytest", "pytest-cov", "pytest-xdist"]
mmsearch = [
    "playwright",
    "requests",
    "matplotlib",
    "duckduckgo_search",
    "langchain",
    "langchain-community",
    "beautifulsoup4",
    "FlagEmbedding",
    "rouge",
]

[tool.setuptools.packages.find]
include = ["lm_eval*"]
exclude = [
    "assets*",
    "benchmark*",
    "docs",
    "dist*",
    "playground*",
    "scripts*",
    "tests*",
    "checkpoints*",
    "project_checkpoints*",
    "debug_checkpoints*",
    "mlx_configs*",
    "wandb*",
    "notebooks*",
    "logs*",
]

[project.scripts]
lm-eval = "lm_eval.__main__:cli_evaluate"

[tool.ruff]
# Set the maximum line length to 240.
line-length = 240

[tool.ruff.lint]
extend-select = ["I", "W605"]

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["lm_eval"]

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = ["F401", "F402", "F403"]
"utils.py" = ["F401"]
